---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: openjdk:jdk-slim
  commands:
  - ./gradlew build
  - ./gradlew dokkaJar
  - ./gradlew sourceJar

- name: sign
  image: openjdk:jdk-slim
  commands:
  - ./gradlew publishDefaultPublicationToMavenRepository
  environment:
    GPG_KEY:
      from_secret: GPG_KEY
    GPG_PASSPHRASE:
      from_secret: GPG_PASSPHRASE
  when:
    event:
    - promote

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: GITHUB_TOKEN
    draft: true
    files: build/repository/com/molikuner/sqldelight/simple-jvm-driver/*/*
    title: ${DRONE_TAG=${DRONE_DEPLOY_TO}}
  when:
    event:
    - promote

...
